### ISSUE TITLE
Can't take back a vote

### ISSUE THREAD

**Issue by soleilpham** [school-of-athens/schoolofathens-world#22]
I accidentally vote for a different side and couldn't take my vote back afterwards.
Also, I think we should try removing previous voting polls because maybe it's not necessary anymore? 
+ people who log in with google can't change their names, meaning identity exposed?

**Comment by Wu-Jinzhou** [comment]
The fact that you can’t take your vote back is actually intentional as we want people to cast their votes carefully. And in real life people can’t take their votes back as well. But would you recommend adding an additional step when users try to vote, like a modal that asks for confirmation, or allowing users to take back their votes?
For previous polls, we will add due dates for polls later, and there will be an option for not showing polls that are due.
For logging in with google, that’s actually a good point. I will rebuild the authentication feature as we shift from react-router-dom to another routing framework, next.js, so that will be fixed then.
Thanks for the feedback!

**Comment by SashimiDaBest** [comment]
I’d say either a confirmation message or allow user to change their vote, not take it back.

**Comment by Wu-Jinzhou** [comment]
Alright, I’ll add a confirmation message then. Thanks for the suggestion!
